apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iceci-manager
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - "pods/log"
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - iceci-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - iceci.io
  resources:
  - '*'
  verbs:
  - '*'
