---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceci-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iceci-operator
  template:
    metadata:
      labels:
        name: iceci-operator
    spec:
      serviceAccountName: iceci-operator
      containers:
      - name: iceci-operator
        image: docker.io/iceci/iceci-operator:alpha5
        imagePullPolicy: Always
        env:
        - name: ICE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "iceci-operator"
        - name: ICE_DYNAMIC_PVC
          value: iceci-dynamic-storage
        - name: ICE_SHARED_PVC
          value: iceci-shared-storage
        - name: ICE_IMAGE_KANIKO
          value: "gcr.io/kaniko-project/executor:v0.16.0"
        - name: ICE_IMAGE_UTILS
          value: "iceci/utils:2"
        - name: ICE_IMAGE_BUILDKIT
          value: "moby/buildkit:v0.6.4-rootless"
        - name: ICE_STEP_SERVICE_ACCOUNT
          value: "iceci-operator-step"
        - name: ICE_DEFAULT_IMAGE_BUILDER
          value: "kaniko"
