---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ice-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ice-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - iceci.io
  resources:
  - '*'
  - runtimeprofiles
  verbs:
  - '*'
- apiGroups:
  - iceai.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - sdk.icetek.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
