---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iceci-operator-step

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iceci-operator-step
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - patch
  - get
  - create
  - delete

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iceci-operator-step
subjects:
- kind: ServiceAccount
  name: iceci-operator-step
roleRef:
  kind: Role
  name: iceci-operator-step
  apiGroup: rbac.authorization.k8s.io
