bases:
- ../../bases/rbac
- ../../bases/operator
- ../../bases/dbsettings
- ../../bases/postgres
- ../../bases/sync
- ../../bases/web

resources:
- postgres_pvc.yaml
- storage_dynamic.yaml
- storage_shared.yaml
- ingress.yaml

images:
- name: iceci/iceci-operator
  newTag: alpha7
- name: iceci/iceci-sync
  newTag: alpha7
- name: iceci/iceci-api
  newTag: alpha7
- name: iceci/iceci-ui
  newTag: alpha7


patchesStrategicMerge:
- postgres_pvc.yaml
- web_service_patch.yaml