apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceci-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iceci-sync
  template:
    metadata:
      labels:
        name: iceci-sync
    spec:
      serviceAccountName: iceci-operator
      containers:
      - name: iceci-sync
        image: docker.io/iceci/iceci-sync:alpha1
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ICECI_MANAGER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "iceci-sync"
        - name: ICECI_DB_USER
          value: user
        - name: ICECI_DB_HOST
          value: iceci-postgres
        - name: ICECI_DB_NAME
          value: iceci
        - name: ICECI_DB_PASS
          value: pass
        - name: ICECI_DB_PORT
          value: "5432"
        - name: ICECI_DB_DIALECT
          value: postgres
