apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceci-ui
  labels:
    name: iceci-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iceci-ui
  template:
    metadata:
      labels:
        name: iceci-ui
    spec:
      containers:
      - name: iceci-ui
        image: docker.io/iceci/iceci-ui:alpha1
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: iceci-ui
spec:
  selector:
    name: iceci-ui
  type: ClusterIP
  ports:
  - protocol: TCP
    name: ui
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iceci
spec:
  rules:
  #  - host: iceci.local
  - http:
      paths:
      - path: /api
        backend:
          serviceName: iceci-api
          servicePort: 80
      - path: /
        backend:
          serviceName: iceci-ui
          servicePort: 80