apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceci-api
  labels:
    app: iceci
    name: iceci-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceci
      name: iceci-api
  template:
    metadata:
      name: iceci-api
      labels:
        app: iceci
        name: iceci-api
    spec:
      restartPolicy: Always
      serviceAccountName: iceci-manager
      containers:
      - name: iceci-api
        image: iceci/iceci-api
        imagePullPolicy: Always
        env:
        - name: ICECI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ICECI_DB_DIALECT
          valueFrom:
            secretKeyRef:
              key: DIALECT
              name: iceci-db-settings
        - name: ICECI_DB_PORT
          valueFrom:
            secretKeyRef:
              key: PORT
              name: iceci-db-settings
        - name: ICECI_DB_HOST
          valueFrom:
            secretKeyRef:
              key: HOST
              name: iceci-db-settings
        - name: ICECI_DB_PASS
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: iceci-db-settings
        - name: ICECI_DB_USER
          valueFrom:
            secretKeyRef:
              key: USER
              name: iceci-db-settings
        - name: ICECI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB
              name: iceci-db-settings
        ports:
        - containerPort: 8000
          name: http