apiVersion: v1
kind: Service
metadata:
  name: iceci-api
  labels:
    app: iceci
    name: iceci-api
spec:
  selector:
    app: iceci
    name: iceci-api
  ports:
  - port: 80
    name: http
    targetPort: http
  type: ClusterIP