apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceci-sync
  labels:
    app: iceci
    name: iceci-sync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iceci
      name: iceci-sync
  template:
    metadata:
      name: iceci-sync
      labels:
        app: iceci
        name: iceci-sync
    spec:
      restartPolicy: Always
      serviceAccountName: iceci-manager
      containers:
      - name: iceci-sync
        image: iceci/iceci-sync
        imagePullPolicy: Always
        env:
        - name: ICECI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: iceci-sync
        - name: ICECI_DB_DIALECT
          valueFrom:
            secretKeyRef:
              key: DIALECT
              name: iceci-db-settings
        - name: ICECI_DB_PORT
          valueFrom:
            secretKeyRef:
              key: PORT
              name: iceci-db-settings
        - name: ICECI_DB_HOST
          valueFrom:
            secretKeyRef:
              key: HOST
              name: iceci-db-settings
        - name: ICECI_DB_PASS
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: iceci-db-settings
        - name: ICECI_DB_USER
          valueFrom:
            secretKeyRef:
              key: USER
              name: iceci-db-settings
        - name: ICECI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB
              name: iceci-db-settings
