apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitwatchers.iceci.io
spec:
  group: iceci.io
  names:
    kind: GitWatcher
    listKind: GitWatcherList
    plural: gitwatchers
    singular: gitwatcher
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            git:
              properties:
                auth:
                  properties:
                    secret:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - secret
                  type: object
                provider:
                  enum:
                  - github
                  - gitlab
                  - gitea
                  type: string
                repositoryURL:
                  type: string
              required:
              - repositoryURL
              type: object
            orphanPipelines:
              type: boolean
            schedule:
              type: string
          required:
          - git
          - schedule
          type: object
        status:
          properties:
            buildNumber:
              format: int64
              type: integer
            knownGitEvent:
              properties:
                commits:
                  items:
                    properties:
                      authorEmail:
                        type: string
                      authorName:
                        type: string
                      date:
                        type: string
                      name:
                        type: string
                      refName:
                        type: string
                      sha:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    - name
                    - sha
                    - refName
                    - authorName
                    - authorEmail
                    - date
                    type: object
                  type: array
                tags:
                  items:
                    properties:
                      authorEmail:
                        type: string
                      authorName:
                        type: string
                      date:
                        type: string
                      name:
                        type: string
                      refName:
                        type: string
                      sha:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    - name
                    - sha
                    - refName
                    - authorName
                    - authorEmail
                    - date
                    type: object
                  type: array
              type: object
            lastSuccessfulJob:
              type: string
            phase:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
