---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerbuilds.iceci.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: Age
    format: date-time
    name: age
    type: date
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    type: string
  - JSONPath: .status.podStatus.name
    description: PodName
    format: byte
    name: podname
    type: string
  group: iceci.io
  names:
    kind: ContainerBuild
    listKind: ContainerBuildList
    plural: containerbuilds
    singular: containerbuild
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            docker:
              properties:
                contextPath:
                  description: Absolute path that will be used as context
                  type: string
                dockerfilePath:
                  description: Absolute path to the dockerfile
                  type: string
                imageName:
                  type: string
                registry:
                  type: string
                tags:
                  description: Tags that will be pushed to registry
                  items:
                    type: string
                  minItems: 1
                  type: array
                user:
                  type: string
              required:
              - contextPath
              - dockerfilePath
              - imageName
              - tags
              - user
              type: object
            dockerSecret:
              type: string
            runtimeProfile:
              type: string
            volumeMounts:
              items:
                properties:
                  name:
                    type: string
                  path:
                    type: string
                  pvcName:
                    type: string
                  subPath:
                    type: string
                required:
                - name
                - pvcName
                type: object
              type: array
          required:
          - docker
          - dockerSecret
          - volumeMounts
          type: object
        status:
          properties:
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            message:
              type: string
            pendingDuration:
              format: int32
              type: integer
            pendingStartedTime:
              format: date-time
              type: string
            phase:
              type: string
            podStatus:
              properties:
                exitCode:
                  description: Pod main container (at index 0) return code
                  format: int32
                  type: integer
                name:
                  description: Name of pod
                  type: string
              type: object
            reason:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
