---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerruns.iceci.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: Age
    format: date-time
    name: age
    type: date
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    type: string
  - JSONPath: .status.podStatus.name
    description: Pod name
    format: byte
    name: podName
    priority: 1
    type: string
  - JSONPath: .status.podStatus.exitCode
    description: ExitWithError code
    format: int32
    name: exitCode
    priority: 1
    type: integer
  group: iceci.io
  names:
    kind: ContainerRun
    listKind: ContainerRunList
    plural: containerruns
    singular: containerrun
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cleanupTTL:
              type: integer
            environment:
              items:
                properties:
                  fromSecret:
                    type: string
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                type: object
              type: array
            files:
              items:
                properties:
                  fromSecret:
                    type: string
                  path:
                    type: string
                required:
                - fromSecret
                - path
                type: object
              type: array
            hosts:
              additionalProperties:
                type: string
              type: object
            image:
              type: string
            imagePullPolicy:
              description: PullPolicy describes a policy for if/when to pull a container
                image
              type: string
            imagePullSecret:
              type: string
            runtimeProfile:
              type: string
            script:
              type: string
            serviceAccountName:
              type: string
            volumeMounts:
              items:
                properties:
                  name:
                    type: string
                  path:
                    type: string
                  pvcName:
                    type: string
                  subPath:
                    type: string
                required:
                - name
                - pvcName
                type: object
              type: array
            workingDir:
              type: string
          required:
          - image
          type: object
        status:
          properties:
            cleanupTime:
              format: date-time
              type: string
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            message:
              type: string
            pendingDuration:
              format: int32
              type: integer
            pendingStartedTime:
              format: date-time
              type: string
            phase:
              type: string
            podStatus:
              properties:
                exitCode:
                  description: Pod main container (at index 0) return code
                  format: int32
                  type: integer
                name:
                  description: Name of pod
                  type: string
              type: object
            reason:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
