apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tasks.icekube.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Phase
    format: byte
    name: phase
    priority: 1
    type: string
  group: icekube.io
  names:
    kind: Task
    listKind: TaskList
    plural: tasks
    singular: task
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoLoad:
              type: boolean
            cleanupTTL:
              format: int64
              type: integer
            configMapEnv:
              items:
                type: string
              type: array
            configMapVolume:
              items:
                type: string
              type: array
            dockerSecret:
              properties:
                secretName:
                  type: string
              required:
              - secretName
              type: object
            env:
              additionalProperties:
                type: string
              type: object
            envFromSecret:
              items:
                properties:
                  envName:
                    description: SecretName of environment variable
                    type: string
                  objectKey:
                    description: Key in config map or secret
                    type: string
                  objectName:
                    description: SecretName of config map or secret
                    type: string
                required:
                - objectName
                type: object
              type: array
            hosts:
              additionalProperties:
                type: string
              type: object
            image:
              type: string
            imagePullSecret:
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              type: object
            resourceRequest:
              properties:
                cpu:
                  type: string
                memory:
                  type: string
              type: object
            script:
              type: string
            secretEnv:
              items:
                type: string
              type: array
            secretVolume:
              items:
                type: string
              type: array
            serviceAccountName:
              type: string
            volumeMounts:
              items:
                properties:
                  name:
                    type: string
                  path:
                    type: string
                  pvcName:
                    type: string
                  subPath:
                    type: string
                required:
                - name
                - pvcName
                type: object
              type: array
            workingDir:
              type: string
          required:
          - image
          type: object
        status:
          properties:
            cleanupTime:
              format: date-time
              type: string
            duration:
              format: int32
              type: integer
            finishedTime:
              format: date-time
              type: string
            initializedTime:
              format: date-time
              type: string
            pendingDuration:
              format: int32
              type: integer
            pendingStartedTime:
              format: date-time
              type: string
            phase:
              type: string
            podName:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
