apiVersion: v1
kind: Service
metadata:
  name: iceci-db
  labels:
    app: iceci
    name: iceci-db
spec:
  selector:
    app: iceci
    name: iceci-db
  ports:
  - port: 5432
    name: postgres
    targetPort: postgres
  type: ClusterIP