resources:
- deployment.yaml
- step_service_account.yaml
- step_rbac.yaml


configMapGenerator:
- name: iceci-operator
  literals:
  - ICECI_WORKSPACE_PVC=iceci-dynamic
  - ICECI_IMAGE_UTILS=iceci/utils
  - ICECI_IMAGE_BUILDKIT=moby/buildkit:v0.7.1
